### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by CydoEntis** [jln13x/tailwindcss-highlights#5]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/jln13x/tailwindcss-highlights/main/highlights/7.svg. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.

**Comment by CydoEntis** [comment]
Preview on website also seems to have same issue with missing highlights 

![image](https://github.com/jln13x/tailwindcss-highlights/assets/22714885/3280eeb2-b249-4ded-be51-b4abf3e61d27)

**Comment by jln13x** [comment]
![CleanShot 2024-07-08 at 22 33 29@2x](https://github.com/jln13x/tailwindcss-highlights/assets/85513960/cd240dcd-f0ff-4b00-983c-a4e588758ba0)

Can you check if the problem still exists? @CydoEntis

**Comment by CydoEntis** [comment]
@jln13x Hey sorry, I realized that the issue just happened to be a short github outage, everything is working as expected. I appreciate the quick response though.
