### ISSUE TITLE
tailwindcss-highlights Word Wrap unexpected behavior

### ISSUE THREAD

**Issue by programming-with-ia** [jln13x/tailwindcss-highlights#6]
[tailwindcss-highlights Playground](https://play.tailwindcss.com/hM0gHS3erl)

![Screenshot 2024-08-23 210949](https://github.com/user-attachments/assets/cd21c35c-52c2-4686-b5cc-d6997186fcb4)

**Comment by jln13x** [comment]
thanks!

**Comment by programming-with-ia** [comment]
> thanks!

@jln13x 

It was my pleasure!
You're welcome.
